name: GCC C++17

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install ninja-build
        run: sudo apt install -y ninja-build

      - name: CMake configure -- Debug
        run: cmake -S . -G Ninja -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug

      - name: Run main tests -- Debug
        run: ./cmake-build-debug/tests/etl-tests
      
      - name: Run all tests -- Debug
        run: cd cmake-build-debug; ctest -VV; cd -

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release
      
      - name: Run main tests -- Release
        run: ./cmake-build-release/tests/etl-tests
      
      - name: Run all tests -- Release
        run: cd cmake-build-release; ctest -VV; cd -
