name: Clang C++20

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install ninja-build
        run: sudo apt install -y ninja-build

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: CMake configure -- Debug
        run: cmake -S . -G Ninja -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -DTETL_BUILD_CPP20=ON -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug

      - name: Run tests -- Debug
        run: cd cmake-build-debug; ctest -VV; cd -

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -DTETL_BUILD_CPP20=ON -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: Run tests -- Release
        run: cd cmake-build-release; ctest -VV; cd -
